[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "GrphicsGritty"
authors = [{name = "Cedar", email = "zzcedar@126.com"}]
dynamic = ["version", "description"]
